// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIiz9LYikbYrKmnj9xohPlRKA2w3FkCNw',
    appId: '1:495089390185:web:f1bbd144bc14216b5148f8',
    messagingSenderId: '495089390185',
    projectId: 'real-esign-2',
    authDomain: 'real-esign-2.firebaseapp.com',
    storageBucket: 'real-esign-2.appspot.com',
    measurementId: 'G-13YCH2FNXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4kOj7Itm_rjNBIz4nMDhk99oa8Wsowzo',
    appId: '1:495089390185:android:c904ec4ffb3dc1b75148f8',
    messagingSenderId: '495089390185',
    projectId: 'real-esign-2',
    storageBucket: 'real-esign-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL3N5SEv8qcz9AulyllLxWq1qUwEgr7CA',
    appId: '1:495089390185:ios:88a6de1d34d2b3dc5148f8',
    messagingSenderId: '495089390185',
    projectId: 'real-esign-2',
    storageBucket: 'real-esign-2.appspot.com',
    iosBundleId: 'com.example.realESign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL3N5SEv8qcz9AulyllLxWq1qUwEgr7CA',
    appId: '1:495089390185:ios:88a6de1d34d2b3dc5148f8',
    messagingSenderId: '495089390185',
    projectId: 'real-esign-2',
    storageBucket: 'real-esign-2.appspot.com',
    iosBundleId: 'com.example.realESign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIiz9LYikbYrKmnj9xohPlRKA2w3FkCNw',
    appId: '1:495089390185:web:ba4850b5561b6e665148f8',
    messagingSenderId: '495089390185',
    projectId: 'real-esign-2',
    authDomain: 'real-esign-2.firebaseapp.com',
    storageBucket: 'real-esign-2.appspot.com',
    measurementId: 'G-FW33WN62P9',
  );

}